spring:
  application:
    name: pioneer-backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/pioneer-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 007787898
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8000
