version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    image: openjdk:21
    container_name: spring-backend
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./pioneer-backend-0.0.1-SNAPSHOT.jar:/app/backend.jar
    working_dir: /app
    command: ["java", "-jar", "backend.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
